sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vignesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vignesh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-3"
  app: "Environments"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-3-753439174488"
  bucket_path: "Environments"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"